spring.application.name=SafePasswordProjectMiph

# Database connection settings with direct environment property fallbacks
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/safe_pw?serverTimezone=Europe/Zurich}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Wvxscytheis=p2007}

# Hibernate / JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Enable resource chaining
spring.web.resources.chain.enabled=true

# Add a content-based hash to static resource URLs
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**


